import type { MetadataRoute } from "next";

export default function manifest(): MetadataRoute.Manifest {
  return {
    // A stable identity for the installed app. Without it the browser derives
    // one from start_url, so changing that would register as a different app
    // and he would end up with two icons on his home screen.
    id: "/",
    name: "Quest",
    short_name: "Quest",
    description: "Words, reading and math practice.",
    start_url: "/",
    scope: "/",
    display: "standalone",
    orientation: "portrait",
    background_color: "#FBFAF6",
    theme_color: "#22A06B",
    icons: [
      { src: "/icons/icon-192.png", sizes: "192x192", type: "image/png", purpose: "any" },
      { src: "/icons/icon-512.png", sizes: "512x512", type: "image/png", purpose: "any" },
      {
        src: "/icons/maskable-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "maskable",
      },
    ],
    // Real captures, regenerated by scripts/screenshots.mjs. Chrome uses these
    // for the richer install dialog. Work screens, never the home screen: these
    // files are served publicly so the dialog can fetch them, and the home
    // screen carries his name and his progress.
    screenshots: [
      {
        src: "/screenshots/lesson.png",
        sizes: "412x915",
        type: "image/png",
        form_factor: "narrow",
        label: "Learn how nonfiction is built, one passage at a time",
      },
      {
        src: "/screenshots/math.png",
        sizes: "412x915",
        type: "image/png",
        form_factor: "narrow",
        label: "Write a number from its words, on a Grade 4 number pad",
      },
    ],
  };
}
